services:
  splunk:
    hostname: splunk
    build:
      context: ./splunk
      dockerfile: Dockerfile
    container_name: splunk
    environment:
#      - SPLUNK_ENABLE_LISTEN=9997
#      - SPLUNK_START_ARGS=--accept-license --no-prompt --answer-yes --seed-passwd password
#      - SPLUNK_USERNAME=admin
#      - SPLUNK_PASSWORD=password
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "password"
    restart: always
    volumes:
      - splunk_etc:/opt/splunk/etc
      - splunk_var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      #- "1514:1514"
      #- "514:514/udp"
    networks:
      - splunk
networks:
  splunk:
    name: splunk
volumes:
  splunk_etc:
    name: splunk_etc
  splunk_var:
    name: splunk_var
